##########################################################################
# MA CONF KITTY PERSO
########################################################################

# BEGIN_KITTY_FONTS
font_family      family='DejaVu Sans Mono' postscript_name=DejaVuSansMono
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME

# Navigation entre fenêtres
map alt+h neighboring_window left
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right

# Déplacer une fenêtre
map alt+shift+h move_window left
map alt+shift+l move_window right
map alt+shift+k move_window up
map alt+shift+j move_window down

# Redimensioner une fenêtre
map alt+shift+left resize_window wider 5
map alt+shift+down resize_window shorter 5
map alt+shift+right resize_window narrower 5
map alt+shift+up resize_window taller 5

# Changer le layout
map alt+tab next_layout
map alt+shift+tab previous_layout

#Création et fermeture de splits
map alt+enter new_window
map alt+w close_window

# Ouvrir et fermer un nouvel onglet
map alt+t new_tab
map alt+q close_tab
map f11 fullscreen
map alt+f11 toggle_fullscreen

#Sélection de tabs
map alt+& goto_tab 1
map alt+é goto_tab 2
map alt+" goto_tab 3
map alt+' goto_tab 4
map alt+( goto_tab 5
map alt+- goto_tab 6
map alt+è goto_tab 7
map alt+_ goto_tab 8
map alt+ç goto_tab 9

#Copy / Paste classiques
map alt+c copy_to_clipboard
map alt+v paste_from_clipboard
